name: Trigger auto deployment for azuremvp-api-jmg

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/azuremvp-api-jmg-AutoDeployTrigger-068a1b7c-1e20-4281-91f5-dd606574c0b0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREMVPAPIJMG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZUREMVPAPIJMG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZUREMVPAPIJMG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acrjmg.azurecr.io
          registryUsername: ${{ secrets.AZUREMVPAPIJMG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZUREMVPAPIJMG_REGISTRY_PASSWORD }}
          containerAppName: azuremvp-api-jmg
          resourceGroup: rg-ktds-jmg
          imageToBuild: acrjmg.azurecr.io/azuremvp-api-jmg:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


