name: Trigger auto deployment for containerapp-api-jmg

# When this action will be executed
# 자동 배포 트리거 주석 처리
# on:
#   # Automatically trigger it when detected changes in repo
#   push:
#     branches: 
#       [ main ]
#     paths:
#     - '**'
#     - '.github/workflows/containerapp-api-jmg-AutoDeployTrigger-fbcff294-ecc5-450a-8921-c8ac6bb287ba.yml'
#
#   # Allow manual trigger 
#   workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CONTAINERAPPAPIJMG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPAPIJMG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPAPIJMG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acrjmg.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPAPIJMG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPAPIJMG_REGISTRY_PASSWORD }}
          containerAppName: containerapp-api-jmg
          resourceGroup: rg-ktds-jmg
          imageToBuild: acrjmg.azurecr.io/containerapp-api-jmg:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


