name: Upload repo to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  upload-to-blob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Upload changed files to Azure Blob Storage
        uses: azure/cli@v2
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
        with:
          inlineScript: |
            for file in $(git diff --name-only HEAD^ HEAD); do
              # .git 디렉토리만 제외 (.github은 포함)
              if [[ "$file" == .git/* || "$file" == .git\\* ]]; then
                continue
              fi
              if [ -f "$file" ]; then
                az storage blob upload \
                  --account-name "$AZURE_STORAGE_ACCOUNT" \
                  --account-key "$AZURE_STORAGE_KEY" \
                  --container-name "$AZURE_STORAGE_CONTAINER" \
                  --file "$file" \
                  --name "$file"
              fi
            done
