name: Upload repo to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  upload-to-blob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Get changed files
        id: changed_files
        run: |
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload changed files to Azure Blob Storage
        uses: azure/cli@v2
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
        with:
          inlineScript: |
            for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}); do
              if [ -f "$file" ]; then
                az storage blob upload \
                  --account-name "$AZURE_STORAGE_ACCOUNT" \
                  --account-key "$AZURE_STORAGE_KEY" \
                  --container-name "$AZURE_STORAGE_CONTAINER" \
                  --file "$file" \
                  --name "$file"
              fi
            done
